import Head from 'next/head';
import Image from 'next/image';
import { gql } from '@apollo/client';
import client from '../src/apollo-client';
import Link from 'next/link';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='p-4 shadow rounded bg-white'>
				<h1 className='text-purple-500 leading-normal'>Next.js</h1>
				<p className='text-gray-500'>with Tailwind CSS</p>
			</div>
		</div>
	);
}

/* export async function getStaticProps() {
	const { data } = await client.query({
		query: gql`
			query MyQuery {
				products {
					edges {
						node {
							id
							onSale
							shortDescription(format: RAW)
							slug
							totalSales
							image {
								mediaItemId
								mediaItemUrl
								slug
								status
								title
								id
							}
							name
						}
					}
				}
			}
		`,
	});

	return {
		props: {
			products: data.products.edges,
		},
	};
}
 */
