import Head from 'next/head';
import Layout from '../src/components/Layout';
import Image from 'next/image';
import { gql } from '@apollo/client';
import client from '../src/apollo-client';
import { GET_ALL_MENUS } from '../src/queries/getMenus';

import Header from '../src/components/Header';

export default function Home({ primaryMenu, footerMenu }) {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Header menu={primaryMenu} />
				<div className='p-4 shadow rounded bg-white'>
					<h1 className='text-purple-500 leading-normal'>Next.js</h1>
					<p className='text-gray-500'>with Tailwind CSS</p>
				</div>
			</Layout>
		</div>
	);
}

export const getStaticProps = async () => {
	const { data } = await client.query({
		query: GET_ALL_MENUS,
	});

	return {
		props: {
			primaryMenu: data.primaryMenu,
			footerMenu: data.footerMenu,
		},
	};
};
