import Head from 'next/head';
import Image from 'next/image';
import styles from './Home.module.scss';
import { gql } from '@apollo/client';
import client from '../src/apollo-client';
import Link from 'next/link';

export default function Home({ products }) {
	let productNames = products.map((product) => (
		<div key={product.node.id}>
			{' '}
			<Link href={`/products/${product.node.slug}`}>{product.node.name}</Link> {product.node.id}{' '}
		</div>
	));

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.rootNew}>Hello</div>
			{productNames}
		</div>
	);
}

export async function getStaticProps() {
	const { data } = await client.query({
		query: gql`
			query MyQuery {
				products {
					edges {
						node {
							id
							onSale
							shortDescription(format: RAW)
							slug
							totalSales
							image {
								mediaItemId
								mediaItemUrl
								slug
								status
								title
								id
							}
							name
						}
					}
				}
			}
		`,
	});

	return {
		props: {
			products: data.products.edges,
		},
	};
}
